language: python

env:
  global:
    CIBW_BUILD_VERBOSITY: 3

matrix:
  include:
    - sudo: required
      services:
        - docker
      env: PIP=pip
    - os: osx
      language: generic
      env: PIP=pip2
  exclude:
    - os: linux

script:
  - $PIP install pip setuptools -U
  - $PIP install git+https://github.com/plasticity-admin/cibuildwheel.git@macos-ssl
  - eval "buildwheel() { cibuildwheel --output-dir wheelhouse >>buildwheel.log 2>&1; }"
  - travis_wait 60 buildwheel || (tail -c 3670016 buildwheel.log && exit 1)
  - tail -c 3670016 buildwheel.log
  - ls wheelhouse
  - $PIP install awscli --upgrade
  - /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)" || true
  - brew install awscli || true
  - aws s3 sync ./wheelhouse/ s3://magnitude.plasticity.ai/wheelhouse/
