language: python

env:
  global:
    CIBW_BUILD_VERBOSITY: 3
    PIP: pip3

language: generic

os:
  - linux
  - osx

matrix:
  exclude:
    - os: linux

script:
  - ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
  - brew install python
  - python --version || true
  - python2 --version || true
  - python3 --version || true
  - pip --version || true
  - pip2 --version || true
  - pip3 --version || true
  - $PIP install pip setuptools -U
  - $PIP install git+https://github.com/plasticity-admin/cibuildwheel.git@macos-ssl
  - eval "buildwheel() { cibuildwheel --output-dir wheelhouse >>buildwheel.log 2>&1; }"
  - travis_wait 60 buildwheel || (tail -c 3670016 buildwheel.log && exit 1)
  - tail -c 3670016 buildwheel.log
  - ls wheelhouse
  - $PIP install awscli --upgrade
  - brew install awscli || true
  - aws s3 sync ./wheelhouse/ s3://magnitude.plasticity.ai/wheelhouse/
